version: "3.0"

services:
  web:
    build: .
    image: psawesome/webserver:default
    ports:
    - 5000:8080

    depends_on:
      - mongo_user
      - rabbit_management_user

  mongo_user:
    image: mongo
    hostname: my-mongo
    ports:
    - 27017:27017

  rabbit_management_user:
    image: rabbitmq:3-management
    hostname: my-rabbit-management
    ports:
      - 5672:5672
      - 15672:15672